steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',

        '--build-arg', 'VITE_SERVER_DOMAIN=https://dev.kalamio.com/',

        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/kalamio/frontend-dev:latest',

        './frontend'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/kalamio/frontend-dev:latest'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'kalamio-web-development',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/kalamio/frontend-dev:latest',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/kalamio/frontend-dev:latest'

options:
  logging: CLOUD_LOGGING_ONLY
